"use client";
import { Footer } from "@/components/Footer";
import "./globals.css";
import { Header } from "@/components/Header";
// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="relative w-full h-full flex flex-col items-center justify-center bg-[#403e3e]"
    >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="max-w-[500px] w-full h-full mb-[8vh] bg-white">
        {children}
      </body>
      <Footer />
    </html>
  );
}
